// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Card from "@rmwc/card";
import * as Typography from "@rmwc/typography";

function App(Props) {
  return React.createElement("div", {
              style: {
                display: "flex",
                height: "100vh",
                alignItems: "center",
                justifyContent: "center"
              }
            }, React.createElement(Card.Card, {
                  children: null,
                  style: {
                    width: "21rem"
                  }
                }, React.createElement(Card.CardPrimaryAction, {
                      children: null
                    }, React.createElement(Card.CardMedia, {
                          sixteenByNine: true,
                          style: {
                            backgroundImage: "url(https://source.unsplash.com/random/1920x1080)"
                          }
                        }), React.createElement("div", {
                          style: {
                            padding: "0 1rem 1rem 1rem"
                          }
                        }, React.createElement(Typography.Typography, {
                              children: "Lorem Ipsum",
                              use: "headline6",
                              tag: "h2"
                            }), React.createElement(Typography.Typography, {
                              children: "By John Doe",
                              use: "subtitle2",
                              style: {
                                marginTop: "-1rem"
                              },
                              tag: "h3",
                              theme: "textSecondaryOnBackground"
                            }), React.createElement(Typography.Typography, {
                              children: "Visit ten places on our planet that are undergoing the biggest changes today.",
                              use: "body1",
                              tag: "div",
                              theme: "textSecondaryOnBackground"
                            }))), React.createElement(Card.CardActions, {
                      children: React.createElement(Card.CardActionButtons, {
                            children: null
                          }, React.createElement(Card.CardActionButton, {
                                children: "Read"
                              }), React.createElement(Card.CardActionButton, {
                                children: "Bookmark"
                              }))
                    })));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
