// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as App$RescriptRmwcExample from "./App.bs.js";

import "./index.css";

import "@rmwc/button/styles";
import "@rmwc/card/styles";
import "@rmwc/typography/styles";
import "@rmwc/avatar/styles";
import "@rmwc/icon/styles";
import "@rmwc/circular-progress/styles";
import "@rmwc/linear-progress/styles";
import "@rmwc/tooltip/styles";
import "@rmwc/textfield/styles";
import "@rmwc/dialog/styles";
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$RescriptRmwcExample.make, {}), root);
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  root$1 as root,
  
}
/*  Not a pure module */
