// Generated by ReScript, PLEASE EDIT WITH CARE


var Portal = {};

var Button = {};

var Card = {};

var CardPrimaryAction = {};

var CardMedia = {};

var CardMediaContent = {};

var CardActions = {};

var CardActionButtons = {};

var CardActionIcons = {};

var CardActionButton = {};

var Typography = {};

var Avatar = {};

var AvatarGroup = {};

var AvatarCount = {};

var RMWC = {
  Portal: Portal,
  Button: Button,
  Card: Card,
  CardPrimaryAction: CardPrimaryAction,
  CardMedia: CardMedia,
  CardMediaContent: CardMediaContent,
  CardActions: CardActions,
  CardActionButtons: CardActionButtons,
  CardActionIcons: CardActionIcons,
  CardActionButton: CardActionButton,
  Typography: Typography,
  Avatar: Avatar,
  AvatarGroup: AvatarGroup,
  AvatarCount: AvatarCount
};

export {
  RMWC ,
  
}
/* No side effect */
